export const messageActionTypes = {
  GET_SUCCESS: 'GET_USER_MSGS_SUCCESS',
  GET_FAILURE: 'GET_USER_MSGS_FAILURE',
  ADD_SUCCESS: 'ADD_MSG_SUCCESS',
  ADD_FAIL: 'ADD_MSG_FAILURE',
  NEW_CHAT: 'START_NEW_CHAT',
  CLEAR_CHAT: 'CLEAR_NEW_CHAT',
  DELETE_ALL_BY_USER: 'DELETE_ALL_BY_USER',
}