export const postActionTypes = {
  GETALL_SUCCESS: "POST_GETALL_SUCCESS",
  GETALL_FAILURE: "POST_GETALL_FAILURE",

  GETBYUSER_SUCCESS: "POST_GETBYUSER_SUCCESS",
  GETBYUSER_FAILURE: "POST_GETBYUSER_FAILURE",

  GETUSERFAVORITES_SUCCESS: "POST_GETUSERFAVORITES_SUCCESS",
  GETUSERFAVORITES_FAILURE: "POST_GETUSERFAVORITES_FAILURE",

  ADD_SUCCESS: "POST_ADD_SUCCESS",
  ADD_FAILURE: "POST_ADD_FAILURE",

  UPDATE_SUCCESS: "POST_UPDATE_SUCCESS",
  UPDATE_FAILURE: "POST_UPDATE_FAILURE",

  DELETE_SUCCESS: "POST_DELETE_SUCCESS",
  DELETE_FAILURE: "POST_DELETE_FAILURE",

  DELETE_ALL_BY_USER: 'DELETE_ALL_BY_USER',

  CLEAR_POST: 'CLEAR_NEW_POST'
}