export const userActionTypes = {
  LOADING: 'USER_ACTION_ATTEMPT',
  CLEAR_ALERT: 'USER_CLEAR_ALERT',
  CLEAR_USER: 'USER_CLEAR_USER',
  
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  VALIDATION_SUCCESS: 'USER_VALIDATION_SUCCESS',
  VALIDATION_FAILURE: 'USER_VALIDATION_FAILURE',
  CLEAR_VALIDATION: 'USER_VALIDATION_CLEAR',

  LOGOUT: 'USER_LOGOUT',

  SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
  
  DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  DELETE_FAILURE: 'USER_DELETE_FAILURE',

  GET_ALL: 'GET_ALL_USERS',
}